### ISSUE TITLE
New instalation error

### ISSUE THREAD

**Issue by inluxc** [EaDesgin/magento2-warehouses#2]
Magento 2.1.3

`  [Zend_Db_Statement_Exception]
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento2`.`warehouseinventory_stock_item`, CONSTRAINT `WAREHOUSEINV_STOCK_ITEM_STOCK_ID_WAREHOUSEINV_STOCK_STOCK_ID` FOREIGN KEY (`stock_id`) REFERENCES `warehouseinven
  tory_stock` (`stock_id`), query was: INSERT INTO `warehouseinventory_stock_item` () VALUES ()`

**Comment by eadesignro** [comment]
Hi,

Can you provide us with more details please. Installation method, other usefull information? 

Thanks,

**Comment by inluxc** [comment]
I used composer to install.. 

Then i deleted an entry in the WAREHOUSEINVENTORY_STOCK_ITEM table and i run setup up again an it worked.

**Comment by eadesignro** [comment]
Hi,

Ok, thanks. We will investigate. Did you have any items (products)?

Thanks,

**Comment by inluxc** [comment]
No, clean installation.

**Comment by eadesignro** [comment]
Ok, That we will test again,

Thanks,

**Comment by inluxc** [comment]
I tried again to install with the command line and i get this.

`[Progress: 199 / 397]
Installing data...
Data install/update:
Module 'Eadesigndev_Eacore':
[Progress: 200 / 397]
Module 'Eadesigndev_Warehouses':
Installing data...


  [Magento\Framework\Exception\LocalizedException]
  Wrong entity ID`

**Comment by eadesignro** [comment]
This should be fixed on dev. I will try to get a new release asap.
